# shellcheck shell=sh
# Traefik dynamic file provider writer for coolify-ssl.

write_traefik_provider() {
  mkdir -p "$DYNAMIC_DIR"
  target="$DYNAMIC_DIR/$PROVIDER_FILE"
  tmp="$target.tmp.$$"
  stamp="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  if [ -r "$PROVIDER_TEMPLATE" ]; then
    sed -e "s|__CERT_NAME__|$CERT_NAME|g" \
        "$PROVIDER_TEMPLATE" >"$tmp"
  else
    cat >"$tmp" <<EOF
# Generated by coolify-ssl — do not edit.
tls:
  certificates:
    - certFile: /traefik/certs/$CERT_NAME.cert
      keyFile: /traefik/certs/$CERT_NAME.key
EOF
  fi
  # Content stamp so file-watch reloads even when cert paths are unchanged after a .leaf flip.
  printf '\n# coolify-ssl generated-at: %s\n' "$stamp" >>"$tmp"
  mv -f "$tmp" "$target"
  log "Traefik provider written: $target"
}
